version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 0
    groups:
      app-dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: "chore"
    labels:
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 0
    groups:
      actions:
        patterns:
          - "*"
    commit-message:
      prefix: "chore"
    labels:
      - "dependencies"
